version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  reviewers:
  - allanice001
  assignees:
  - allanice001
  ignore:
  - dependency-name: sphinx
    versions:
    - 3.4.3
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: twine
    versions:
    - 3.3.0
    - 3.4.0
  - dependency-name: pip-tools
    versions:
    - 5.5.0
    - 6.0.0
    - 6.0.1
  - dependency-name: watchdog
    versions:
    - 1.0.2
    - 2.0.0
    - 2.0.1
    - 2.0.2
  - dependency-name: pygments
    versions:
    - 2.7.4
    - 2.8.0
  - dependency-name: pytest
    versions:
    - 6.2.2
