language: python
dist: trusty
python: 3.6
env:
  - TOXENV=py36
# - TOXENV=docs
install:
  - pip install tox pip-tools
  - pip compile requirements-dev.in
before_script:
  - python internal/generate.py
script:
  - tox
