language: python
cache: pip
dist: trusty
matrix:
    include:
      - env: TOXENV=py34
        python: 3.4
      - env: TOXENV=py35
        python: 3.5
      - env: TOXENV=py36
        python: 3.6
      - env: TOXENV=py37
        python: 3.7
        dist: xenial
        sudo: true

install:
  - pip install tox pip-tools
  - pip-compile requirements-dev.in
before_script:
  - python internal/generate.py
script:
  - tox
  - coverage run paver test_all
after_success:
  - pip install codecov
  - bash <(curl -s https://codecov.io/bash)
